/opt/awesome/logs/awesome.log {
    su awesome awesome
    size 50M
    rotate 7
    daily
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 awesome awesome
}
